name: CI - Python App with Docker

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Flake8
        run: pip install flake8

      - name: Lint with flake8
        run: flake8 app/ --max-line-length=120

  docker:
    name: Build and Push Docker Image
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: $\{{ secrets.DOCKERHUB_USERNAME }}
          password: $\{{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: $\{{ secrets.DOCKERHUB_USERNAME }}/fastapi-app:latest